// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listDirectory: (path: string) => typedError<FileEntry[], string>(__TAURI_INVOKE("list_directory", { path })),
	readFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { path })),
	writeFile: (path: string, contents: string) => typedError<null, string>(__TAURI_INVOKE("write_file", { path, contents })),
	createFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("create_file", { path })),
	createDirectory: (path: string) => typedError<null, string>(__TAURI_INVOKE("create_directory", { path })),
	renamePath: (oldPath: string, newPath: string) => typedError<null, string>(__TAURI_INVOKE("rename_path", { oldPath, newPath })),
	deleteFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_file", { path })),
	deleteDirectory: (path: string, recursive: boolean) => typedError<null, string>(__TAURI_INVOKE("delete_directory", { path, recursive })),
	copyPath: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("copy_path", { from, to })),
	movePath: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("move_path", { from, to })),
	/**
	 *  Moves an entry to the OS trash rather than unlinking it, so a mistaken
	 *  delete stays recoverable from Finder/Explorer. `delete_file` and
	 *  `delete_directory` remain the permanent-delete primitives.
	 */
	trashPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("trash_path", { path })),
	/**
	 *  Copies an entry alongside itself under a free name, returning the path it
	 *  landed at. Picking that name here rather than in the frontend keeps the
	 *  check and the create in one step -- a caller that probed for a free name
	 *  first could still lose the race to the watcher, another window, or Finder.
	 */
	duplicatePath: (path: string) => typedError<string, string>(__TAURI_INVOKE("duplicate_path", { path })),
	exists: (path: string) => __TAURI_INVOKE<boolean>("exists", { path }),
	/**
	 *  Writes an attachment's bytes into `dir` under a free name derived from
	 *  `file_name`, creating the directory if it does not exist yet, and returns
	 *  the path it landed at.
	 * 
	 *  The name is resolved here rather than on the frontend for the same reason
	 *  `duplicate_path` does it: a caller that probed for a free name first could
	 *  still lose the race to another window or to Finder.
	 */
	saveAttachment: (dir: string, fileName: string, contents: number[]) => typedError<string, string>(__TAURI_INVOKE("save_attachment", { dir, fileName, contents })),
	/**
	 *  Copies a file that is already on disk into `into_dir`, under a free name,
	 *  and returns where it landed.
	 * 
	 *  The counterpart to `save_attachment` for the file-picker path: the bytes
	 *  stay in the backend rather than making a round trip through the webview.
	 */
	importAttachment: (from: string, intoDir: string) => typedError<string, string>(__TAURI_INVOKE("import_attachment", { from, intoDir })),
	listWorkspaceFilesRecursive: (path: string) => typedError<FileEntry[], string>(__TAURI_INVOKE("list_workspace_files_recursive", { path })),
	/**
	 *  Opening a workspace is also what starts watching it, so the two can never
	 *  drift apart. Returns an error if the watcher could not be started -- on
	 *  Linux a large vault can exhaust the inotify watch limit, and the frontend
	 *  needs to know it is running without live updates rather than assume it is.
	 */
	setWorkspace: (path: string) => typedError<null, string>(__TAURI_INVOKE("set_workspace", { path })),
	/**
	 *  Makes the folder for a new workspace, `name` inside `parent`, and returns
	 *  its path. An empty folder of that name is fine (it may have been made by
	 *  hand for this); one with anything in it is refused, so a new workspace
	 *  never adopts someone else's files.
	 */
	createWorkspace: (parent: string, name: string) => typedError<string, string>(__TAURI_INVOKE("create_workspace", { parent, name })),
	/**
	 *  Where new workspaces go unless the user picks somewhere else: Documents,
	 *  or home when there's no Documents folder.
	 */
	defaultWorkspaceParent: () => __TAURI_INVOKE<string | null>("default_workspace_parent"),
	getWorkspace: () => __TAURI_INVOKE<string | null>("get_workspace"),
	/**
	 *  Grants `asset:` access to one file outside the open workspace.
	 * 
	 *  `set_workspace` only allows the workspace directory, so a file opened
	 *  through the file dialog from anywhere else resolves to a perfectly
	 *  well-formed `asset:` URL that the scope then denies -- a blank image or a
	 *  PDF that never loads, with nothing in the console to explain it. Viewers
	 *  call this before building the URL. Allowing a single file the user has
	 *  explicitly opened is the narrowest grant that fixes it.
	 */
	allowAssetPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("allow_asset_path", { path })),
	/**
	 *  Starts or stops watching the current workspace, backing the
	 *  `explorer.watchFilesystem` setting. Turning it off has to reach the OS
	 *  watcher itself -- muting the events on the frontend would leave the real
	 *  cost (a recursive watch over a network share or a very large vault) exactly
	 *  where it was.
	 */
	setWatchEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_watch_enabled", { enabled })),
	getCommandRegistry: () => __TAURI_INVOKE<CommandMeta[]>("get_command_registry"),
	setKeybind: (commandId: CommandId, accelerator: string) => typedError<null, string>(__TAURI_INVOKE("set_keybind", { commandId, accelerator })),
	/**  Drop a command's override so it falls back to its compiled-in default. */
	clearKeybind: (commandId: CommandId) => typedError<null, string>(__TAURI_INVOKE("clear_keybind", { commandId })),
	/**
	 *  Release the native menu's key equivalents so the frontend can record a
	 *  keystroke that the OS would otherwise consume before the webview sees it.
	 *  Menu items stay visible and clickable throughout.
	 */
	setMenuAcceleratorsEnabled: (enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_menu_accelerators_enabled", { enabled })),
	getMenuLayout: () => __TAURI_INVOKE<ResolvedMenu[]>("get_menu_layout"),
	/**
	 *  Commands whose accelerator is dispatched by the OS before the webview
	 *  ever sees the keystroke. Only macOS installs a native menu, so every
	 *  other platform leaves the whole registry to the frontend; the frontend
	 *  binds exactly what is missing from this list, which keeps one
	 *  accelerator to one dispatcher and rules out double-firing.
	 */
	getNativeMenuCommandIds: () => __TAURI_INVOKE<CommandId[]>("get_native_menu_command_ids"),
	/**
	 *  Every user-authored theme visible right now: the ones in the open workspace
	 *  and the ones in the app data dir, which follow the user between workspaces.
	 */
	listUserThemes: () => typedError<UserThemeFile[], string>(__TAURI_INVOKE("list_user_themes")),
	/**
	 *  The directory a user theme should be dropped into, created on demand so the
	 *  settings pane can offer to reveal it.
	 */
	ensureThemeDir: (scope: string) => typedError<string, string>(__TAURI_INVOKE("ensure_theme_dir", { scope })),
	/**
	 *  Every font family installed on this machine, sorted and deduplicated.
	 * 
	 *  Enumerating families walks the system font directories, which is slow
	 *  enough to be worth keeping off the startup path -- the frontend calls this
	 *  lazily the first time a font control is opened and caches the result.
	 */
	listSystemFonts: () => typedError<string[], string>(__TAURI_INVOKE("list_system_fonts")),
	syncServerInfo: (server: string) => typedError<SyncServerInfo, string>(__TAURI_INVOKE("sync_server_info", { server })),
	syncSignIn: (server: string) => typedError<null, string>(__TAURI_INVOKE("sync_sign_in", { server })),
	syncSignOut: (server: string) => typedError<null, string>(__TAURI_INVOKE("sync_sign_out", { server })),
	/**  Who's signed in to `server`, or `None` when nobody is. */
	syncAccount: (server: string) => typedError<string | null, string>(__TAURI_INVOKE("sync_account", { server })),
	syncVaults: (server: string) => typedError<SyncVault[], string>(__TAURI_INVOKE("sync_vaults", { server })),
	syncCreateVault: (server: string, name: string) => typedError<SyncVault, string>(__TAURI_INVOKE("sync_create_vault", { server, name })),
	/**  An API token for Atlas (it can only list vaults and create notes). */
	syncCreateToken: (server: string, name: string) => typedError<string, string>(__TAURI_INVOKE("sync_create_token", { server, name })),
	/**  Links the window's workspace to a vault and starts syncing it. */
	syncLink: (server: string, vaultId: string, vaultName: string) => typedError<SyncLinkReport, string>(__TAURI_INVOKE("sync_link", { server, vaultId, vaultName })),
	/**
	 *  Stops syncing the window's workspace and forgets its link. Its files
	 *  stay as they are.
	 */
	syncUnlink: () => typedError<null, string>(__TAURI_INVOKE("sync_unlink")),
	/**  The window's workspace's sync, or `None` if it isn't linked. */
	syncStatus: () => typedError<{
	server: string,
	vault_id: string,
	vault_name: string,
	device: string,
	state: string,
	message: string | null,
	reviews: number,
} | null, string>(__TAURI_INVOKE("sync_status")),
	syncReconnect: () => typedError<null, string>(__TAURI_INVOKE("sync_reconnect")),
	syncReviews: () => typedError<SyncReview[], string>(__TAURI_INVOKE("sync_reviews")),
	syncReviewVersions: (id: string) => typedError<SyncVersions, string>(__TAURI_INVOKE("sync_review_versions", { id })),
	/**  Clears a review, first saving `text` as the note if given. */
	syncResolveReview: (id: string, text: string | null) => typedError<null, string>(__TAURI_INVOKE("sync_resolve_review", { id, text })),
	syncEditorOpened: (path: string, text: string) => __TAURI_INVOKE<void>("sync_editor_opened", { path, text }),
	/**
	 *  An editor loaded (or reloaded) a file's text. Its later saves are merged
	 *  against exactly this.
	 *  The sync vault each folder is linked to (`None` if it isn't), so a
	 *  `solstice://open?vault=` link finds a folder by its vault's name even
	 *  when the folder is named differently.
	 */
	syncVaultNames: (paths: string[]) => __TAURI_INVOKE<(string | null)[]>("sync_vault_names", { paths }),
};

/** Events */
export const events = {
	fileSystemChanged: makeEvent<FileSystemChanged>("file-system-changed"),
	keymapChanged: makeEvent<KeymapChanged>("keymap-changed"),
	menuCommand: makeEvent<MenuCommand>("menu-command"),
	syncChanged: makeEvent<SyncChanged>("sync-changed"),
};

/* Types */
export type CommandId = "app.settings" | "file.new_note" | "file.new_canvas" | "file.open_file" | "file.new_tab" | "file.new_folder" | "file.new_workspace" | "file.import_from_sync" | "file.manage_workspaces" | "file.open_folder" | "file.close_tab" | "file.reveal_in_explorer" | "file.reveal_in_system" | "file.open_in_default_app" | "file.copy_path" | "file.copy_relative_path" | "file.copy_wikilink" | "file.rename" | "file.duplicate" | "file.move_to" | "file.delete" | "edit.bold" | "edit.italic" | "edit.inline_code" | "edit.strikethrough" | "edit.highlight" | "edit.find" | "edit.heading1" | "edit.heading2" | "edit.heading3" | "edit.heading4" | "edit.heading5" | "edit.heading6" | "edit.blockquote" | "edit.bullet_list" | "edit.ordered_list" | "edit.task_list" | "edit.indent" | "edit.outdent" | "edit.code_block" | "edit.hard_break" | "edit.paragraph" | "edit.insert_image" | "edit.insert_wikilink" | "edit.copy_block_link" | "view.toggle_sidebar" | "view.toggle_source_mode" | "navigation.back" | "navigation.forward" | "canvas.new_text" | "canvas.new_file" | "canvas.new_group" | "canvas.zoom_to_fit" | "canvas.zoom_to_selection" | "canvas.toggle_snap" | "canvas.toggle_minimap";

export type CommandMeta = {
	id: CommandId,
	label: string,
	/**
	 *  The accelerator in effect: the compiled-in default, or the user's
	 *  override when `is_overridden`.
	 */
	accelerator: string | null,
	is_overridden: boolean,
};

export type FileEntry = {
	name: string,
	path: string,
	is_dir: boolean,
};

/**  One debounced batch of changes under `root`. */
export type FileSystemChanged = {
	root: string,
	changes: FsChange[],
};

export type FsChange = {
	kind: FsChangeKind,
	/**  The path as it stands now. For `Renamed`, the destination. */
	path: string,
	/**  Only set for `Renamed`. */
	from: string | null,
	/**
	 *  Statted at emit time, so the frontend needs no follow-up call.
	 *  `None` exactly when the path no longer exists.
	 */
	entry: FileEntry | null,
};

export type FsChangeKind = "Created" | "Modified" | "Removed" | "Renamed";

/**
 *  Fired whenever the resolved keymap changes (an override was saved).
 *  Every frontend consumer of the keymap — titlebar, tinykeys, the Milkdown
 *  keymap plugin — listens for this instead of polling.
 */
export type KeymapChanged = null;

/**
 *  A registry command was activated from the native menu bar -- either by
 *  click or by the OS dispatching its accelerator. The frontend runs it
 *  through the same handler registry a keybind would, so both paths are
 *  indistinguishable downstream.
 */
export type MenuCommand = CommandId;

/**
 *  OS-provided editing actions. Deliberately NOT CommandMeta -- no id in
 *  the command registry, no rebindable accelerator, never registered as
 *  a keybind. A real Ctrl+C/Ctrl+Z keystroke is already handled natively
 *  by the browser/ProseMirror with zero JS involved; the only thing that
 *  actually needs wiring per-platform is a MENU CLICK on one of these
 *  (mac: free via the native menu, Windows: needs a small real handler
 *  in the React menu bar -- see NativeItem below for the label/accel
 *  shown there).
 */
export type NativeItem = "Undo" | "Redo" | "Cut" | "Copy" | "Paste" | "SelectAll";

export type ResolvedMenu = {
	title: string,
	entries: ResolvedMenuEntry[],
};

export type ResolvedMenuEntry = ({ Command: CommandMeta }) & { Native?: never; Submenu?: never } | ({ Native: {
	item: NativeItem,
	label: string,
	accelerator: string,
} }) & { Command?: never; Submenu?: never } | "Separator" | ({ Submenu: {
	title: string,
	entries: ResolvedMenuEntry[],
} }) & { Command?: never; Native?: never };

/**  Something about a workspace's sync changed (status, reviews): ask again. */
export type SyncChanged = {
	root: string,
};

/**
 *  `state` is `connecting`, `syncing`, `synced`, `offline`, `signed_out`,
 *  `relink` or `deleted`.
 */
export type SyncInfo = {
	server: string,
	vault_id: string,
	vault_name: string,
	device: string,
	state: string,
	message: string | null,
	reviews: number,
};

export type SyncLinkReport = {
	same: number,
	downloaded: number,
	uploaded: number,
	kept_both: string[],
};

export type SyncReview = {
	id: string,
	path: string | null,
	/**
	 *  `overlap` (two devices edited the same text) or `restored` (edited
	 *  on one device while deleted on another).
	 */
	kind: string,
	/**  Unix milliseconds. */
	at: number | null,
	device: string,
};

export type SyncServerInfo = {
	version: string,
	/**  `oidc` or `dev` (a development server: no sign-in). */
	auth: string,
	signed_in: boolean,
};

export type SyncVault = {
	id: string,
	name: string,
};

export type SyncVersions = {
	base: string | null,
	local: string | null,
	remote: string | null,
	merged: string,
};

/**
 *  One theme file as found on disk. The contents are handed over unparsed:
 *  validating here would split the rules across two languages, and the
 *  frontend already owns the token allowlist that decides what a theme may
 *  declare.
 */
export type UserThemeFile = {
	path: string,
	/**  `"workspace"` or `"global"`, for the badge on the theme card. */
	source: string,
	contents: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

