// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listDirectory: (path: string) => typedError<FileEntry[], string>(__TAURI_INVOKE("list_directory", { path })),
	readFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { path })),
	writeFile: (path: string, contents: string) => typedError<null, string>(__TAURI_INVOKE("write_file", { path, contents })),
	createFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("create_file", { path })),
	createDirectory: (path: string) => typedError<null, string>(__TAURI_INVOKE("create_directory", { path })),
	renamePath: (oldPath: string, newPath: string) => typedError<null, string>(__TAURI_INVOKE("rename_path", { oldPath, newPath })),
	deleteFile: (path: string) => typedError<null, string>(__TAURI_INVOKE("delete_file", { path })),
	deleteDirectory: (path: string, recursive: boolean) => typedError<null, string>(__TAURI_INVOKE("delete_directory", { path, recursive })),
	copyPath: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("copy_path", { from, to })),
	movePath: (from: string, to: string) => typedError<null, string>(__TAURI_INVOKE("move_path", { from, to })),
	exists: (path: string) => __TAURI_INVOKE<boolean>("exists", { path }),
	setWorkspace: (path: string) => __TAURI_INVOKE<void>("set_workspace", { path }),
	getWorkspace: () => __TAURI_INVOKE<string | null>("get_workspace"),
	getCommandRegistry: () => __TAURI_INVOKE<CommandMeta[]>("get_command_registry"),
	setKeybind: (commandId: CommandId, accelerator: string) => typedError<null, string>(__TAURI_INVOKE("set_keybind", { commandId, accelerator })),
	getMenuLayout: () => __TAURI_INVOKE<ResolvedMenu[]>("get_menu_layout"),
};

/** Events */
export const events = {
	keymapChanged: makeEvent<KeymapChanged>("keymap-changed"),
};

/* Types */
export type CommandId = "file.new_note" | "file.open_file" | "file.new_tab" | "file.new_folder" | "file.open_folder" | "file.close_tab" | "edit.bold" | "edit.italic" | "edit.inline_code" | "edit.strikethrough" | "edit.heading1" | "edit.heading2" | "edit.heading3" | "edit.heading4" | "edit.heading5" | "edit.heading6" | "edit.blockquote" | "edit.bullet_list" | "edit.ordered_list" | "edit.code_block" | "edit.hard_break" | "edit.paragraph" | "view.toggle_sidebar" | "navigation.back" | "navigation.forward";

export type CommandMeta = {
	id: CommandId,
	label: string,
	default_accelerator: string | null,
};

export type FileEntry = {
	name: string,
	path: string,
	is_dir: boolean,
};

/**
 *  Fired whenever the resolved keymap changes (an override was saved).
 *  Every frontend consumer of the keymap — titlebar, tinykeys, the Milkdown
 *  keymap plugin — listens for this instead of polling.
 */
export type KeymapChanged = null;

/**
 *  OS-provided editing actions. Deliberately NOT CommandMeta -- no id in
 *  the command registry, no rebindable accelerator, never registered as
 *  a keybind. A real Ctrl+C/Ctrl+Z keystroke is already handled natively
 *  by the browser/ProseMirror with zero JS involved; the only thing that
 *  actually needs wiring per-platform is a MENU CLICK on one of these
 *  (mac: free via the native menu, Windows: needs a small real handler
 *  in the React menu bar -- see NativeItem below for the label/accel
 *  shown there).
 */
export type NativeItem = "Undo" | "Redo" | "Cut" | "Copy" | "Paste" | "SelectAll";

export type ResolvedMenu = {
	title: string,
	entries: ResolvedMenuEntry[],
};

export type ResolvedMenuEntry = ({ Command: CommandMeta }) & { Native?: never; Submenu?: never } | ({ Native: {
	item: NativeItem,
	label: string,
	accelerator: string,
} }) & { Command?: never; Submenu?: never } | "Separator" | ({ Submenu: {
	title: string,
	entries: ResolvedMenuEntry[],
} }) & { Command?: never; Native?: never };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

